
server.port=${PORT:8085}
server.servlet.context-path=/

spring.application.name=chatbot

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false


gemini.api.key=${GEMINI_API_KEY:AIzaSyBmS_QKsal4De5zl503M9_MJkvDDYWmJog}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent

