package com.example.chatbot.model;

/**
 * Model class representing a chat response from the backend.
 * Contains the response message generated by the Gemini API.
 */
public class ChatResponse {
    private String response;

    // Default constructor
    public ChatResponse() {
    }

    // Constructor with response
    public ChatResponse(String response) {
        this.response = response;
    }

    // Getter and Setter
    public String getResponse() {
        return response;
    }

    public void setResponse(String response) {
        this.response = response;
    }
}

